### ISSUE TITLE
[DataCap Application] <zhejiangweitu> - <technology>

### ISSUE THREAD

**Issue by wangchen138** [Blockchain-World-News/FIL-DC-Allocator#28]
### Version

1

### DataCap Applicant

zhejiangweitu

### Project ID

018

### Data Owner Name

zhejiangweitu

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

N/A

### Social Media Handle

N/A

### Social Media Type

WeChat

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

2PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1kahahzgmuoy6htokiwq5pejlo3tmaqkqvevt56q

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We leverage our parent company's expertise in computer hardware and software infrastructure design to establish ourselves as a leading provider of professional computer technology services, a manufacturer of blockchain products, and a distributor of electronic commercial display solutions. We are actively engaged in blockchain technology research and employ cutting-edge methods to integrate blockchain computing into devices like smart homes and HVAC equipment. By harnessing the power of idle devices through specialized computing modules, we enhance our computational capabilities while keeping costs minimal. Furthermore, we offer remote monitoring software for these blockchain devices, ensuring a secure and efficient control system. Our philosophy is rooted in professionalism and excellence, evident in our diverse range of intelligent commercial display products and integrated solutions that cater to the TV and surveillance industries.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
DEV DATA
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
https://drive.google.com/file/d/17zB2loGKl8ou3JuMjYSbm5SIsG1xT4c9/view?usp=sharing

https://drive.google.com/file/d/1H5jU2bvAxS9cdn7WK7Y9hTP5guiC6V_t/view?usp=sharing

https://drive.google.com/file/d/1yd6WpiFFTMjAyTnMCEv0yDN11a6sMNNH/view?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer, Venus built-in data transfer

### How did you find your storage providers

Slack, Filmine, Big Data Exchange, Partners, Others

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02980903 KR
f02827694 Mainland China
f02827151 Mainland China
f03001085 HK
will disclose in the comment when the sps are ready
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by psh0691** [comment]
Hi @wangchen138 
Thank you for applying for DC allocation.

I'd like to ask you a few additional questions before DC allocation.

1. @wangchen138's GitHub activity is private. Therefore, I have difficulty validating the client. Can you make it public? 

2. The type of data you want to save is "Private Commercial/Enterprise", do you want to save it privately? Can you save it and retrieve it?

3. Have you ever applied for DC with a previous LDN? If so, please let me know the link as well.

**Comment by psh0691** [comment]
![스크린샷, 2024-07-23 18-33-19](https://github.com/user-attachments/assets/e226ee2f-3210-4878-9cc0-64430004954e)

**Comment by wangchen138** [comment]
Hello @psh0691 ,

> @wangchen138's GitHub activity is private. Therefore, I have difficulty validating the client. Can you make it public?

My profile is now public. sorry for the inconvenience. 

> The type of data you want to save is "Private Commercial/Enterprise", do you want to save it privately? Can you save it and retrieve it?

Yes, the data we will store now is private data that we will encrypt it. Data can be retrieved and downloaded but cannot be opened due to encryption unless decrypted. 

> Have you ever applied for DC with a previous LDN? If so, please let me know the link as well.

Here's the previous application I have applied https://github.com/VenusOfficial/Pathway-VFDA/issues/26

**Comment by gimims** [comment]
As far as I know, you did not provide a website, which is required. Encrypted data needs to be submitted to the official https://github.com/fidlabs/Open-Data-Pathway/issues

**Comment by psh0691** [comment]
@wangchen138 
Encrypted personal and enterprise data cannot be applied to the public data storage DC allocator.

Please understand this.

**Comment by wangchen138** [comment]
> @wangchen138 Encrypted personal and enterprise data cannot be applied to the public data storage DC allocator.
> 
> Please understand this.

@psh0691 
I applied here because I saw this pathway accepts all kinds of data. 
`17. What type(s) of data would be applicable for your pathway?
Public Open Dataset (Research/Non-Profit),Public Open Commercial/Enterprise,Private Commercial/Enterprise,Private Non-Profit/Social Impact`  -- from your application form. 
please correct me if i'm wrong.

**Comment by psh0691** [comment]
@wangchen138 
It was intended to limit the DC allocation of private individual/company data to Korea. 
![스크린샷, 2024-07-24 21-43-21](https://github.com/user-attachments/assets/70f6024c-c73b-4536-aa50-a19071aafc0d)

This is because in the case of foreign companies, it is difficult to obtain KYB proof according to the characteristics of each country. Even in the case of data to be stored by private/company, it is difficult to verify, so we intend to limit this.

Please understand.

**Comment by wangchen138** [comment]
Understood. i will close this issue. thanks for your reply!
