### ISSUE TITLE
[DataCap Application] <FileTech> - <European Union>

### ISSUE THREAD

**Issue by nike-mp** [Blockchain-World-News/FIL-DC-Allocator#32]
### Version

1

### DataCap Applicant

FileTech

### Project ID

FileTech-02

### Data Owner Name

European Union

### Data Owner Country/Region

Luxembourg

### Data Owner Industry

Life Science / Healthcare

### Website

https://data.europa.eu/en

### Social Media Handle

https://data.europa.eu/en

### Social Media Type

Twitter

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

1024TiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1idq3ryonivnqcwckagyqh6eww7bnldmbh6325ry

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FileTech focuses on providing excellent data storage solutions. We have a passionate and knowledgeable team with extensive experience and expertise in the field of data storage. Whether it's data storage, data management, data recovery, or data center design and construction, we possess abundant technical capabilities and solutions.

At FileTech, we understand the importance of data in modern businesses. We not only offer high-performance data storage devices and solutions, but also provide comprehensive data management tools to help clients efficiently organize, classify, and protect their data assets.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The European Data organization, led by the EU, offers a broad range of datasets across various fields, such as environment, economy, healthcare, and demographics. These datasets support research, policy-making, and innovation, aiming to increase transparency and stimulate growth through data-driven approaches. The data is designed for easy use across different sectors and regions within the EU.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
https://data.europa.eu/data/datasets/b0203a76-ab90-4564-9789-9b7c21fb9c65~~1
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02368946 BeiJing
f02362412 California
f02639492 California
f02822222 Hong Kong
f03166666 Hongkong
f03166668 Hongkong
f03068013-HK
f03035686-GuangDong
f01926635-SiChuang
f01999119-SiChuang
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by psh0691** [comment]
@nike-mp 

Thank you for applying for DC.

Could you please let me know the specific details of SP for distributing data using DC?

Account, SP Company Name, Country and Region, Relationship

**Comment by nike-mp** [comment]
Hey, I responded to your question a week ago. Why is it not displayed here? It may be a network problem.
sorry.

**Comment by nike-mp** [comment]
We have modified and re-completed the sp information, what else do I need to do?

**Comment by psh0691** [comment]
1. Which country is Filetech located in? Is it Chaina?
2. Is Filetech the storage provider of Filecoin?
3. Why did you apply to me in Korea when there are several DC Allocator in China?
4. Have you applied for DC before? If you have one, please send me a link.
5. Is there a reason to distribute the data on AWS in an inefficient hard drive or otherwise?
